### ISSUE TITLE
Picked up skulls don't drop

### ISSUE THREAD

**Issue by BrainStone** [EvModder/DropHeads#31] opened 2021-04-20 21:23 UTC
Some mobs can pick up items. This includes skulls. However if these mobs are then killed the skull doesn't drop.

This effect can be easily seen when farming WitherSekeltons and having many in one spot. A skull drops, one of the remaining skeletons picks it up and instead of dropping the skull when dying it just drops it's normal loot.

Other picked up items work fine, just skulls are an issue.

I fixed it temporarily by preventing pickups, but it would be awesome if this could be fixed!

**Comment by EvModder** [comment] 2021-04-21 07:39
Ah thanks for noticing this!  This exact issue used to happen a long time ago but it got fixed, looks like it got reintroduced recently.
I should be able to get this fixed in v3.5.5 which should be ready to publish by the end of this week

**Comment by BrainStone** [comment] 2021-04-21 10:01
Awesome! Thanks for fixing that so quickly.

Are there any dev builds?

**Comment by EvModder** [comment] 2021-04-23 06:23
Sorry, I've been postponing responding to your comment because I was trying to finish the full release of the next version, but the changes are too big for me to finish as quickly as I was hoping.

In the meantime, here is a dev build from yesterday that includes the fix. It has some settings in the config that I will probably change the values of before the full release, so when that gets finished and published on Bukkit I recommend deleting all the config files (or renaming them to save a copy) so it generates new ones, then copy over any settings you care about.

https://github.com/EvModder/DropHeads/tree/master/dev-build-3.6.0

**Comment by EvModder** [comment] 2021-04-23 06:41
The annoying thing about this bug is it turned out it wasn't DropHead's fault, but rather the Bukkit/Spigot API.
The code was basically doing this:
```
1. in EntityDeathEvent:
2. remove all dropped skulls/heads (to avoid double-dropping with vanilla drops)
3. if (guaranteedToDrop(entity.helmet)) { re-add entity's helmet to the dropped items }
```
The issue is `entity.getEquipment().getHelmet()` on returns "AIR" even when they are wearing one of their buddy's skulls.
I created [this bug](https://hub.spigotmc.org/jira/browse/SPIGOT-6431) to let the Spigot team know, and I'm using a work-around fix for the meantime.

**Comment by BrainStone** [comment] 2021-04-23 19:21
Well they are not wearing the heads. They are holding them in the hand. I see nothing wrong with that.

**Comment by EvModder** [comment] 2021-04-24 00:19
Oh, well the changes I made earlier will fix that too, but I'll double-check with some testing

**Comment by BrainStone** [comment] 2021-04-30 09:37
I just noticed that the plugin automatically updates. And in addition has no version identifier in the file name, so as it turns out I've been unknowingly using that version for quite a while.

As a rule of thumb, automatic updates that replace files should never be enabled by default. Leave the user in control of their binaries. And even more so don't download experimental files. And if you insist on doing that, at least version them properly so people actually know when a file has been updated.

**Comment by BrainStone** [comment] 2021-05-01 00:32
Seems to work. However it announces those redropped skulls as well, which is very confusing. Could you fix that too? 😅

**Comment by EvModder** [comment] 2021-05-04 22:02
I uploaded the v3.6.1 release to the Bukkit plugin page, let me know if that works; I'll also test it tonight to make sure it's fixed.

**Comment by BrainStone** [comment] 2021-05-06 20:35
Looks good 👍🏼

**Comment by BrainStone** [comment] 2021-05-10 21:15
Bad news. It looks like redropped heads still get announced.  
I'm sure of it because when farming I often get multiple drop messages when there are many skeletons but just one skull in the chest.

Do you want me to make a new issue for that?

**Comment by EvModder** [comment] 2021-05-13 03:20
This issue can track it, thanks for re-opening the bug, I'll test some more and see what's happening.
Maybe it's an issue where two heads get dropped in the same gametick and are merged, but that's just a guess in the dark...

**Comment by BrainStone** [comment] 2021-05-14 00:22
There's definately just one. Like once I got 4 drop messages in total but just one skull.

**Comment by EvModder** [comment] 2021-05-15 05:42
Can you send me a schematic of the farm you're using and maybe your configuration file as well?
I've get this bug to occur for myself but haven't managed to yet

**Comment by EvModder** [comment] 2021-07-04 04:03
Closing this issue for now because I can't get it to happen for me and no one else has reported it..
Feel free to reopen if you can help me find a way to get it to happen so I can debug it further

**Closed by EvModder** 2021-07-04 04:03 UTC
Labels: bug

**Comment by BrainStone** [comment] 2021-07-06 00:25
No problem. I think it might have been due to me using an outdated version.
