### ISSUE TITLE
heads dropping at 10% for all users

### ISSUE THREAD

**Issue by Redd56** [EvModder/DropHeads#3] opened 2020-05-25 04:30 UTC
simple as that

**Comment by EvModder** [comment] 2020-05-27 20:40
strange, can you elaborate? is it like that for all mob types? if you turn on debug messages in the console, does it say 10% there as well?

**Comment by EvModder** [comment] 2020-06-06 04:23
Closing since I cannot reproduce this bug

**Closed by EvModder** 2020-06-06 04:23 UTC

**Comment by Redd56** [comment] 2020-06-07 10:17
I think it was a config error it just kinda sorted itself out
