### ISSUE TITLE
Wither skulls not dropping after most recent update

### ISSUE THREAD

**Issue by MasterShifu99** [EvModder/DropHeads#79] opened 2022-09-13 15:57 UTC
Wither skulls wont drop at all in this most recent update.  We are getting the other heads but no wither skulls.  

Could not pass event EntityDeathEvent to DropHeads v3.7.7.1
java.lang.StringIndexOutOfBoundsException: begin 20, end 8, length 8
	at java.lang.String.checkBoundsBeginEnd(String.java:4604) ~[?:?]
	at java.lang.String.substring(String.java:2707) ~[?:?]
	at java.lang.String.substring(String.java:2680) ~[?:?]
	at net.evmodder.DropHeads.JunkUtils.getSpawnCauseMult(JunkUtils.java:63) ~[DropHeads (3).jar:?]
	at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:165) ~[DropHeads (3).jar:?]
	at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:270) ~[DropHeads (3).jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-142]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:877) ~[paper-1.19.2.jar:git-Paper-142]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1748) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1645) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1322) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2067) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2982) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2904) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-142]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-142]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-142]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-142]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-142]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1309) ~[paper-1.19.2.jar:git-Paper-142]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[paper-1.19.2.jar:git-Paper-142]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-142]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by EvModder** [comment] 2022-09-18 10:52
Sorry my response here is 5 days late -- There were actually several related bugs for this same issue, and the update which should fix them v3.7.7.2 was released the same day as this report, can you let me know if that version works for you?
If not, reply back and I'll try to handle it asap

**Comment by MasterShifu99** [comment] 2022-09-18 11:16
I just tried it out again a few days ago and it still conflicted.

**Comment by EvModder** [comment] 2022-09-21 21:49
Is it giving that same console error as posted above?
I'm having trouble re-creating this issue in my test world, can you share your DH config in a PM here or on Bukkit or in a pastebin?

**Comment by EvModder** [comment] 2022-10-04 23:12
I'm going to close this bug since I haven't been able to reproduce it in testing, if you (or anyone else) experiences it again please feel free to reopen the bug and share the error/repro

**Closed by EvModder** 2022-10-04 23:12 UTC
