### ISSUE TITLE
Crash from config setup

### ISSUE THREAD

**Issue by BluePhoenixGame** [EvModder/DropHeads#5] opened 2020-08-01 18:54 UTC
Hi, the plugin worked the first time starting. Then I edited the config and restarted and now this:
```
[18:50:00 INFO]: [DropHeads] Enabling DropHeads v3.3.7
[18:50:00 ERROR]: Error occurred while enabling DropHeads v3.3.7 (Is it up to date?)
java.lang.NullPointerException: null
        at net.evmodder.DropHeads.commands.CommandDropRate.<init>(CommandDropRate.java:29) ~[?:?]
        at net.evmodder.DropHeads.DropHeads.onEvEnable(DropHeads.java:89) ~[?:?]
        at net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:29) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
I don't know what I did sorry...

**Comment by BluePhoenixGame** [comment] 2020-08-01 19:01
Here are my config files 
[head-drop-rates.txt](https://github.com/EvModder/DropHeads/files/5011097/head-drop-rates.txt)
[head-textures.txt](https://github.com/EvModder/DropHeads/files/5011098/head-textures.txt)
[spawn-cause-modifiers.txt](https://github.com/EvModder/DropHeads/files/5011099/spawn-cause-modifiers.txt)
```
# How to announce beheadings, options are GLOBAL, LOCAL, DIRECT, or OFF
behead-announcement-mobs: 'GLOBAL'
behead-announcement-players: 'GLOBAL'

# Replaces death messages if player behead announcement is GLOBAL
behead-announcement-replaces-death-message: true

# The messages used to announce beheading
message-beheaded: '&6${VICTIM}&r was decapitated'
message-beheaded-by-entity: '&6${VICTIM}&r was decapitated by &6${KILLER}&r'
message-beheaded-by-entity-with-item: '&6${VICTIM}&r was decapitated by &6${KILLER}&r'
message-beheaded-by-entity-with-item-named: '&6${KILLER}&r decapitated &6${VICTIM}&r using &7${ITEM}&r'
message-beheaded-item-display-format: '${RARITY}[${NAME}${RARITY}]'

# Whether to drop heads when not killed by a player
drop-for-nonplayer-kills: false

# Whether to drop heads if killed by projectile weapon from a player
# Only checked if 'drop-for-nonplayer-kills' is false
drop-for-ranged-kills: false

# Whether to drop heads for any death cause if last-damager is a player
# Only checked if 'drop-for-nonplayer-kills' is false
drop-for-indirect-kills: true

# Only drop player heads (you can also do this in 'head-drop-rates.txt'
# by making all mobs except players have a 0% chance of dropping heads)
player-heads-only: false

# Only drop "simple" mob heads (one per EntityType), without any unique
# features based on mob traits or subtype; very boring, not recommended
simple-mob-heads-only: false

# Whether to keep entity heads updated with the latest vanilla textures
refresh-textures: true

# Whether to reset the item name for a head when refreshing its texture
refresh-item-names: false

# When a player changes their skin, should old heads be updated to the
# new texture? Note: to trigger refresh, heads must be mined or dropped
update-on-skin-change: false

# Track mob spawn reasons, edits drop rates using 'spawn-cause-modifiers.txt'
track-mob-spawns: true

# Enable the mechanic where the first mob killed by a charged creeper's
# explosion will drop its head with 100% probability
# Note: This overrides 'drop-for-nonplayer-kills', but not 'player-heads-only'
charged-creeper-drops: true

# A Minecraft easter egg is that mobs named 'Dinnerbone' or 'Grumm' are
# upside down.. If you want their heads to share this trait, set to true
drop-grumm-heads: true
show-grumm-in-tab-complete: false

# Enable plugin auto-updates (checks for new versions and head textures)
# Note: Disable if your console shows DropHeads errors on startup
update-plugin: true

# Run in debug mode (prints extra information to console)
debug-messages: true

# Shows information about a head when right-clicked by a player
head-click-listener: true
head-click-format-mobs: "&7[&6DropHeads&7]&f That's ${A} ${NAME} ${TYPE}"
head-click-format-players: "&7[&6DropHeads&7]&f That's ${NAME}'s Head"

# Saves lore of heads in GameProfile when placed (used by some other plugins)
# Only works for player-type heads, eg: won't work for minecraft:creeper_head
# WARNING: This feature is in BETA and is relatively untested
# NOTE: Lore currently is lost when the head is broken by a non-player
save-custom-lore: false

# Displays the type of head (eg: player, mob, HDB) in the head item's lore
# Note: Applies to custom player/mob heads, but not to WITHER_SKULL etc.
show-head-type-in-lore: true

# Only drop heads if the killer used an axe; overrides 'must-use'
must-use-axe: false

# (Optional) Select weapons required to be used in order to get heads to drop
# If this list is empty, any weapon can be used to get heads
must-use:
#  - IRON_SWORD
#  - DIAMOND_AXE
#  - WOOD_HOE

# Drop chances are multiplied by this number for each level of looting
looting-mutliplier: 1.01

# This number is added to the drop chance for each level of looting
looting-addition: 0.0

# Use vanilla behavior (overrides 'looting-mult/add') for wither skeletons
vanilla-wither-skeleton-looting-behavior: true

# Replace Zombie_Pigman heads with Zombified_Piglin heads in 1.16+
update-zombie-pigman-heads: true

# (Optional) Let certain tools have a higher chance of beheading
# The number is the percent increase in drop chance when using that tool
# Eg: 0.8 = 80% more likely, -0.1 = 10% less likely, 2.0 = +200%, etc.
specific-tool-modifiers:

# (Optional) Modify head drop chance based on how long a mob has been alive
# Format is "X: V", where if the mob has been alive for X or more time, then
# the drop rate is increased by V percent (similar to above; can be negative)
time-alive-modifiers:

# Whether to enable logging for certain events
log:
  enable: true
  filename: 'dropheads-log.txt'
  log-mob-behead: true
  log-mob-behead-format: '${TIMESTAMP},mob decapitated,${VICTIM},${KILLER},${ITEM}'
  log-player-behead: true
  log-player-behead-format: '${TIMESTAMP},player decapitated,${VICTIM},${KILLER},${ITEM}'
  log-head-command: true
  log-head-command-format: '${TIMESTAMP},gethead command,${SENDER},${HEAD}'
```
Can't upload a yml file.

**Comment by BluePhoenixGame** [comment] 2020-08-01 19:57
I might know why. ```
PLAYER:             0
UNKNOWN: 0.0
```
Player is a float, but I set it to a 0 to disable player head drops fully. I redid my configs and except from leaving `specific-tool-modifiers:` and `time-alive-modifiers:` as in having one item set to 1, I set PLAYER to 0.0

**Comment by chris998** [comment] 2020-08-01 22:10
i'm on 1.15.2 I also get a crash.

01.08 17:05:41 [Server] Server thread/INFO [DropHeads] Enabling DropHeads v3.3.7
01.08 17:05:41 [Server] Server thread/ERROR Error occurred while enabling DropHeads v3.3.7 (Is it up to date?)
01.08 17:05:41 [Server] INFO java.lang.NoClassDefFoundError: Lme/arcaniax/hdb/api/HeadDatabaseAPI;
01.08 17:05:41 [Server] INFO at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at java.lang.Class.getField0(Class.java:2975) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at java.lang.Class.getField(Class.java:1701) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at net.evmodder.EvLib.FileIO.installedEvPlugins(FileIO.java:47) ~[?:?]
01.08 17:05:41 [Server] INFO at net.evmodder.EvLib.FileIO.verifyDir(FileIO.java:58) ~[?:?]
01.08 17:05:41 [Server] INFO at net.evmodder.EvLib.EvPlugin.reloadConfig(EvPlugin.java:21) ~[?:?]
01.08 17:05:41 [Server] INFO at net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:28) ~[?:?]
01.08 17:05:41 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
01.08 17:05:41 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.arcaniax.hdb.api.HeadDatabaseAPI
01.08 17:05:41 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO ... 17 more

**Comment by EvModder** [comment] 2020-08-04 22:50
Were you able to confirm this?
Either way I think this is a bug I should fix (because float vs int should cause a crash)

Thanks for pointing it out :)

**Comment by BluePhoenixGame** [comment] 2020-08-08 00:18
I think this is the root cause actually
>  I redid my configs and except from leaving specific-tool-modifiers: and time-alive-modifiers: as in having one item set to 1, I set PLAYER to 0.0

These two were empty. Now I have one item in each but they don't actually change anything (set to 1).

**Comment by EvModder** [comment] 2020-08-13 22:53
> These two were empty. Now I have one item in each but they don't actually change anything (set to 1).
Do you mean the drop rate is set to 1 but the heads are not dropping 100% of the time?
let me know if this is still not working and explain the issue, and I'll do my best to fix it :)

**Comment by BluePhoenixGame** [comment] 2020-08-15 11:53
`specific-tool-modifiers` and `time-alive-modifiers` were empty when this happened, now they are not. But rather I have one item in the list that is just set to 1. So that's it's empty (because it doesn't change anything) but in reality not.

**Comment by EvModder** [comment] 2020-08-21 03:58
I think this is fixed in the current versions, let me know if anything like it happens for you again though :)

**Closed by EvModder** 2020-08-21 03:58 UTC
Labels: bug
