### ISSUE TITLE
Message doesn't show when I get a head + I always get a head when I kill a mob

### ISSUE THREAD

**Issue by Tyox-x** [EvModder/DropHeads#96] opened 2023-06-25 13:42 UTC
Very good plugins but I encountered 2 problems. The first is that the message when someone kill a mob and get a head doesn't pop up. The second is that when I kill a mob, using any kind of item (sword, axe... without enchantments), I have like a 100% drop rate, I always get a head when I kill a mob. I tried to remove the plugin, to redownload the plugin, I've checked the drop head rate file but I hadn't modify anything at all. I have other plugins than DropHeads on my server but on 1.19 everything was functionning right and now in 1.20, I have this 2 issues that I can't solve. So, on my 1.20 server I tried to remove all plugins one by one but it seems like none of the plugins were causing this 2 issues. I also tried to use v3.7.12 instead of the new version but didn't change anything. Idk what to do, but very cool plugin btw.

**Comment by steven11304** [comment] 2023-06-26 22:42
There is a specific-tool-multipliers:  option 
So If you use sword diamond axe will multiply the drop rate

**Comment by EvModder** [comment] 2023-07-01 00:14
Check the output of the `/droprate` command while looking at a mob - it's probably a permission issue, some permission management plugins are a bit goofy and give server ops the perm for `dropheads.alwaysbehead` even though it's configured to be false by default, but you can get around them by setting it to false explicitly.

As for the missing messages - that could be caused by conflicts with other plugins that override death messages (most of the CustomDeathMessages-type plugins do this), you can get around it by having the behead message *in addition* to the death message by setting `behead-announcement-replaces-player-death-event-message: false`, but I'd also recommend making sure you're running the latest version of DropHeads + the other plugin.

**Comment by EvModder** [comment] 2023-07-13 20:14
(marking as closed since I cannot recreate this issue without more info, feel free to DM me or reopen if you still need help with it)

**Closed by EvModder** 2023-07-13 20:14 UTC
