### ISSUE TITLE
Server Crashed From Plugin

### ISSUE THREAD

**Issue by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [EvModder/DropHeads#100] opened 2023-07-22 16:39 UTC
https://mclo.gs/TNAzYGV
Yeah

**Comment by EvModder** [comment] 2023-07-22 21:41
Looks like it's stuck requesting profile/skin lookups, which can be slow if the server has high ping to the Mojang API / Skin servers and the cache rate is bad.

An easy (although perhaps awkward) fix would be to set `refresh-textures` to false in the `config.yml` for DropHeads, which will skip the skin lookup check that occurs when a head item is dropped.

**Comment by EvModder** [comment] 2023-07-22 21:43
I'm actually working on a more general solution to this problem, which will make requests to Mojang's skin servers asynchronously (in a different thread) and only update textures when the skin is immediately available in the cache.  This won't be an option in the config until v3.7.14 is released though

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment] 2023-07-22 22:41
> An easy (although perhaps awkward) fix would be to set `refresh-textures` to false in the `config.yml` for DropHeads, which will skip the skin lookup check that occurs when a head item is dropped.

The heads would still have the player skins though right ?

**Comment by EvModder** [comment] 2023-07-23 04:53
Yep, they just wouldn't try to update the skin when they get dropped or placed

**Comment by EvModder** [comment] 2023-07-23 07:35
Update:
I've gone ahead and finished the async profile lookup I mentioned earlier, it can be enabled using [this line in the config.yml](https://github.com/EvModder/DropHeads/blob/965de76f84e922e98d2b636e42e5c3b6f26af69b/config.yml#L260)

Currently only available in the [v3.7.14 dev jar](https://github.com/EvModder/DropHeads/raw/master/DropHeads_v3.7.14.jar) which I just posted.
Once I've had time to test it more thoroughly and finish 1 other WIP feature for the v..14 release I'll post it on Bukkit as well

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment] 2023-07-23 11:14
> Yep, they just wouldn't try to update the skin when they get dropped or placed
So the skin of a player is being cached only once and even if they change skin it will drop the old head ?

Oh also here are another couple of bugs I noticed:
You can't place heads on floor 
There's a double kill message on decapitation, one for regular kill and second for decapitation

It would also appear that there's no discordsrv hook so no decapitation messages go through discord, I personally would like to see that in future.

**Comment by EvModder** [comment] 2023-07-24 00:03
Oh yeah I think I saw your message about those on Bukkit.

Placing heads on the floor -- It sounds like a config setting you might have accidentally enabled.

Double message on decapitation -- This was an issue with Paper/Purpur servers in 1.20+, it should be fixed now in [v3.8.0](https://dev.bukkit.org/projects/dropheads/files/4661054), as long as you have [this setting](https://github.com/EvModder/DropHeads/blob/839782161434080f47717a7f2350e7078bfd6d1b/config.yml#L19) set to `true` and player beheads announcement set to 'GLOBAL'.

I'm curious about a DiscordSRV hook; I haven't looked at their API before (since I've only every used [EssentialsDiscord](https://essentialsx.net/wiki/Discord-Tutorial.html) personally), but certainly sounds like something worth doing.
So with DiscordSRV, there is currently absolutely nothing about the decapitation showing up in the linked channel right?

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment] 2023-07-24 11:10
Yeah, that's correct, nothing about decapitation shows in the discord chat.
I also couldn't find any relevant settings in config that could affect floor placement, so yeah. If you have any clues, I would gladly test.

**Comment by EvModder** [comment] 2023-07-25 02:26
Hmm, the floor placement issue could be caused by `[prevent-head-placement: true](https://github.com/EvModder/DropHeads/blob/839782161434080f47717a7f2350e7078bfd6d1b/config.yml#L115)` in the config.yml (that would be my first guess), I suppose it could also be caused by some other permission plugin, or anti-illegal-items plugin, if you have anything else like that.

Another way to check is to temporarily move all plugins to another folder (or move the server jar to a new folder) and run the server with just DropHeads with fresh config file (by moving/deleting the current one so it generates a new one) and see if it works there, and then by process of elimination see what other plugin is messing with it, in which case you can let me know and I'll see if it's a compatibility thing I can fix on my end (or if I need to reach out to some other developer)

**Comment by EvModder** [comment] 2023-07-25 20:16
No worries, if you ever figure out which one is causing it just contact the plugin author (or myself).

I'm going to close this issue though because the original problem has been answered.

**Closed by EvModder** 2023-07-25 20:16 UTC
