### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by pjindras** [EvModder/DropHeads#106] opened 2024-01-18 14:58 UTC
Hello, my server crashed, and the plugin made suspicious activity, so maybe there could be a bug.

Log: https://paste.gg/p/anonymous/606dd2a7205148bbba08a3eb928d51ae

Server version: Current: git-Purpur-2095 (MC: 1.20.2)*
Previous: git-Purpur-2062 (MC: 1.20.1)

Using proxy Velocity: Velocity 3.3.0-SNAPSHOT (git-eabff202-b327)

Plugin version: DropHeads v3.9.0

**Comment by EvModder** [comment] 2024-01-18 18:23
Ahh yeah looks like lag caused by Mojang API lookup calls (DropHeads checks for name/skin change by default, although this can be disabled in the config).

I very recently ([v3.9.0](https://dev.bukkit.org/projects/dropheads/files/4957365)) fixed an issue with caching profile lookups which should've drastically reduced this, but I guess not enough / in all cases.

There's a few potential ways to fix this in the config.yml:
`async-offline-profile-requests: true` - since the cause of the issue is the MC server having a high ping to the Mojang API server(s), this will generally fix things by having it do the lookups in the background instead of realtime. The only downside is a bit of head/texture glitchiness or delayed updating.

In case you don't already have it (it's false by default), setting `update-on-skin-change: false` can also help reduce the lookups.

(BTW, i'm currently working on a broader fix for this with offline-caches with configurable expiration - currently, the profile cache gets cleared when the server or plugin restarts/reloads, which means it's more susceptible to cache-lookup-spam-lag right after restarting)

**Closed** 2024-01-27 19:29 UTC
