### ISSUE TITLE
Console Error when killing goats

### ISSUE THREAD

**Issue by Solzay** [EvModder/DropHeads#78] opened 2022-09-08 22:08 UTC
[22:01:30 ERROR]: Could not pass event EntityDeathEvent to DropHeads v3.7.7.1
java.lang.StringIndexOutOfBoundsException: begin 20, end 8, length 8
        at java.lang.String.checkBoundsBeginEnd(String.java:4601) ~[?:?]
        at java.lang.String.substring(String.java:2704) ~[?:?]
        at java.lang.String.substring(String.java:2677) ~[?:?]
        at net.evmodder.DropHeads.JunkUtils.getSpawnCauseMult(JunkUtils.java:63) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:165) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:270) ~[DropHeads.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-135]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:877) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1748) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1645) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1322) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2067) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2984) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2906) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1309) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-135]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by EvModder** [comment] 2022-09-09 05:27
This should be fixed in [DropHeads v3.7.7.1](https://dev.bukkit.org/projects/dropheads/files/3964253), at least when I tested it, can you try it and let me know?

**Comment by EvModder** [comment] 2022-09-09 05:29
I think this error is a duplicate of #75, but I just realized that the fix for it might have not gotten included in the Bukkit release, so I guess I'll release a v3.7.7.2

**Comment by felix642** [comment] 2022-09-11 17:50
Precisely what I was going to ask! We are currently waiting for the latest version to fix that issue and I was wondering when you would have time to update the plugin.

**Comment by EvModder** [comment] 2022-09-18 10:50
Sorry I forgot to ping here (5 days late), but just wanted to say in case it was missed that the update (which should in theory fix this) is available now on Bukkit

**Closed by EvModder** 2022-09-18 10:50 UTC
