### ISSUE TITLE
When renaming a magma head it becomes a HeadsDatabase head, do you know how to fix it?

### ISSUE THREAD

**Issue by thiagogebrimm** [EvModder/DropHeads#89] opened 2022-12-10 03:19 UTC
![image](https://user-images.githubusercontent.com/75040244/206826635-52f8d45c-1a1d-4c19-96ba-8659d2a82d51.png)

**Comment by EvModder** [comment] 2022-12-10 10:59
Hmm, sorry I do not know how to fix this, perhaps it is a compatibility issue with the HeadsDatabase plugin?
Please let me know what versions of each plugin you are using (put the version numbers in a reply please) and I'll try it as well; maybe I can also try reaching out to the author of the HDB plugin and see if he knows anything about it as well

**Comment by thiagogebrimm** [comment] 2022-12-10 13:34
HeadDatabase-4.17.0
and
DropHeads v3.7.8

**Comment by EvModder** [comment] 2022-12-11 17:07
Hmm, I haven't been able to get it to happen for me, maybe @Brennian has some ideas?
(I think he has a support Discord, it might be a good idea to ask him there as well, I'm not entirely sure how HDB assigns uuids to its heads)

**Comment by EvModder** [comment] 2023-12-12 16:59
Does the issue still happen @thiagogebrimm?

**Comment by EvModder** [comment] 2024-01-27 12:05
Closing the bug since there's been no other reports of this in the past year+

Feel free to reopen if the issue is still occurring and/or you find a way to reproduce it

**Closed by EvModder** 2024-01-27 12:05 UTC
Labels: bug, Compatibility
